backend:
  name: github
  # change repo to your git repository url
  repo: pixelstrolch/fvw_site

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: settings
    label: Einstellungen
    files:
      - name: config
        label: Allgemein
        file: site-meta-data.json
        fields:
          - widget: string
            name: title
            label: Titel der Website
            required: true
          - widget: string
            name: siteUrl
            label: Adresse der Website
            required: true
          - widget: text
            name: description
            label: Beschreibung
            default: ""
            required: false
          - widget: object
            name: home
            label: Startseiten Optionen
            fields:
              - widget: string
                name: title
                label: Titel
                default: ""
                required: false
              - widget: markdown
                name: description
                label: Beschreibung
                default: ""
                required: false
              - widget: image
                name: homeImg
                label: Grosses Startseitenbild
                hint: "Empfohlene Auflösung: 1280x800"
                required: false
                media_library:
                  config:
                    multiple: false
  - name: blog
    label: Blog
    folder: content/blog
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - { label: Template, name: template, widget: hidden, default: BlogPost }
      - name: path
        label: Path
        widget: string
        pattern: [/]
        hint: "Path must start with /"
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - label: Meta Description
        name: metaDescription
        widget: text
        required: false
      - label: Featured Image
        name: thumbnail
        widget: image
        hint: "Image size 1280x800 works best :)"
        required: false
        media_library:
          config:
            multiple: false
      - { name: body, label: Body, widget: markdown }
