backend:
  name: git-gateway
  repo: pixelstrolch/fvw_site
  branch: main

media_folder: static/uploads
public_folder: /uploads

locale: "de"

collections:
  - name: settings
    label: Seiteneinstellungen
    files:
      - name: config
        label: Allgemein
        file: site-meta-data.json
        fields:
          - widget: string
            name: title
            label: Titel der Website
            required: true
          - widget: string
            name: siteUrl
            label: Adresse der Website
            required: true
          - widget: text
            name: description
            label: Beschreibung
            default: ""
            required: false
      - name: home
        label: Startseite
        file: content/homepage-data.json
        fields:
          - name: title
            label: Titel
            widget: string
            default: ""
            required: true
          - name: description
            label: Beschreibung
            widget: markdown
            default: ""
            required: true
  - name: blog
    label: Beiträge
    folder: content/blog
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - name: template
        label: Template
        widget: hidden
        default: BlogPost
      - name: path
        label: Pfad
        widget: string
      - name: date
        label: Datum
        widget: datetime
      - name: title
        label: Titel
      - name: metaDescription
        label: Beschreibe diesen Beitrag in ein bis zwei Sätzen (Suchmaschinenoptimierung)
        widget: text
      - name: featuredImage
        label: Beitragsbild
        required: false
        widget: object
        fields:
          - name: thumbnail
            label: Beitragsbild
            widget: image
            required: false
            media_library:
              config:
                multiple: false
          - name: alt
            label: Alt text (Was ist auf dem Bild zu sehen in ein, zwei Sätzen?)
            widget: string
            required: false
      - name: body
        label: Body
        widget: markdown
