backend:
  name: github
  # change repo to your git repository url
  repo: pixelstrolch/fvw_site

media_folder: static/uploads
public_folder: /uploads

locale: "de"

collections:
  - name: settings
    label: Seiteneinstellungen
    files:
      - name: config
        label: Allgemein
        file: site-meta-data.json
        fields:
          - widget: string
            name: title
            label: Titel der Website
            required: true
          - widget: string
            name: siteUrl
            label: Adresse der Website
            required: true
          - widget: text
            name: description
            label: Beschreibung
            default: ""
            required: false
      - name: home
        label: Startseite
        file: homepage-data.json
        fields:
          - widget: string
            name: title
            label: Titel
            default: ""
            required: false
          - widget: markdown
            name: description
            label: Beschreibung
            default: ""
            required: false
          - widget: image
            label: heroImage
            name: Startseitenbild
            required: false
            media_library:
              config:
                multiple: false
  - name: blog
    label: Beiträge
    folder: content/blog
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - { label: Template, name: template, widget: hidden, default: BlogPost }
      - name: path
        label: Path
        widget: string
        pattern:
          [
            "^[a-z0-9]+(?:-[a-z0-9]+)*$",
            "Darf keine Leerzeichen oder Sonderzeichen und Umlaute enthalten.",
          ]
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - label: Meta Description
        name: metaDescription
        widget: text
        required: false
      - label: Beitragsbild
        name: thumbnail
        widget: image
        required: false
        media_library:
          config:
            multiple: false
      - { name: body, label: Body, widget: markdown }
